version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/fe"
    schedule:
      interval: "weekly"
  - package-ecosystem: "bundler"
    directory: "/be"
    schedule:
      interval: "weekly"
