version: '3'
services:
  fe:
    build: ./fe
    ports:
      - "8080:8080"
    container_name: fe
    volumes:
      - ./fe:/fe # アプリケーションファイルの同期
      - /fe/node_modules
    command: yarn run dev

  api: # Ruby on Railsが起動するコンテナ
    container_name: api
    build: ./be
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000' # localhostの3000ポートでアクセスできるようにする
    volumes:
      - ./be:/be # アプリケーションファイルの同期
    depends_on:
      - db
    stdin_open: true
    tty: true

  db: # MySQLが起動するコンテナ
    container_name: db
    platform: linux/x86_64 # M1 Mac OS
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d/my.cnf
    command: --default-authentication-plugin=mysql_native_password # 認証方式(8系以前)
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'

volumes:
  mysql_data:
    driver: local
