require:
  - rubocop-rails
  - rubocop-performance
Rails:
  Enabled: true
inherit_gem:
  rubocop-discourse: default.yml
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - 'Gemfile.lock'
    - 'vendor/**/*'
