version: '3'
services:
  gql-server: # Ruby on Railsが起動するコンテナ
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000' # localhostの3000ポートでアクセスできるようにする
    volumes:
      - .:/be # アプリケーションファイルの同期
    depends_on:
      - db
    stdin_open: true
    tty: true
  db: # MySQLが起動するコンテナ
    platform: linux/x86_64 # M1チップ対応のため追記
    image: mysql:8.0
    volumes:
      # - mysql-data:/var/lib/mysql # データの永続化
      - mysql_data:/var/lib/mysql
      - ./mysql/config:/etc/mysql/conf.d/my.cnf
    command: --default-authentication-plugin=mysql_native_password # 認証方式を8系以前のものにする。
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
      # MYSQL_DATABASE: 'be_development'
volumes:
  mysql_data:
    driver: local
