# frozen_string_literal: true
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative 'config/application'
# graphql condegen
require 'graphql/rake_task'

Rails.application.load_tasks

# graphql condegen
GraphQL::RakeTask.new(schema_name: 'BeSchema', directory: Rails.root.join('graphql/gen'))
