name: lint_unit-test

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - 'main' # master に対してPR作成した時(例: issues/xxx)

jobs:
  lint_unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Install dependencies
        working-directory: ./fe
        run: yarn install --frozen-lockfile --prefer-offline
      - name: Run lint
        working-directory: ./fe
        run: yarn lint
      - name: Run test
        working-directory: ./fe
        run: yarn test
      - name: fail notify
        if: failure()
        # v1.1.0
        uses: tokorom/action-slack-incoming-webhook@1517f0a4db0ccb231ffbef9237747e7800c20c41
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: failed STG test & build
          attachments: |
            [
              {
                "color": "danger",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "fields": [
                  {
                    "title": "Pull Request title",
                    "value": "${{ github.event.pull_request.title }}"
                  },
                  {
                    "title": "Pull Request URL",
                    "value": "https://github.com/${{ github.repository }}/pull/${{ github.event.number }}"
                  },
                  {
                    "title": "GitHub Actions URL",
                    "value": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                ]
              }
            ]

  notify:
    runs-on: ubuntu-latest
    needs: lint_unit-test
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Slack Notification on SUCCESS
        # v1.1.0
        uses: tokorom/action-slack-incoming-webhook@1517f0a4db0ccb231ffbef9237747e7800c20c41
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: Successfully lint, test
          attachments: |
            [
              {
                "color": "good",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "fields": [
                  {
                    "title": "Pull Request title",
                    "value": "${{ github.event.pull_request.title }}"
                  },
                  {
                    "title": "Pull Request URL",
                    "value": "https://github.com/${{ github.repository }}/pull/${{ github.event.number }}"
                  },
                  {
                    "title": "GitHub Actions URL",
                    "value": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                ]
              }
            ]
